Repository ppodgorsek/docker-robot-framework, pull requests merged in 2018-03, with the labels that each got.

#64 Issue #63 - Cannot build the project
  Dockerfile
Labels: bug

#66 Issue #61 - Suite 'Tests' contains no tests
  README.md
Labels: documentation

#67 Allow passing robot options via environment variable
  .travis.yml
  README.md
  bin/run-tests-in-virtual-screen.sh
Labels: enhancement

#70 Added Faker 4.2.0 to the Robot Framework toolchain
  Dockerfile
  README.md
Labels: enhancement

#75 Issue #74 - Update Firefox to version 59.0
  Dockerfile
  README.md
Labels: enhancement

#72 Added chromedriver troubleshooting for known issue
  README.md
Labels: enhancement

#78 Issue #77 - Add info about accessing the logs to troubleshoot
  README.md
Labels: documentation

#79 Issue #73 - Update SeleniumLibrary to version 3.1.1
  Dockerfile
  README.md
Labels: enhancement
