Repository ppodgorsek/docker-robot-framework, pull requests merged in 2020-01, with the labels that each got.

#227 Issue #226 - Upgrade FTP library to version 1.8
  Dockerfile
  README.md
Labels: enhancement

#228 Issue #208 - Allow tests for emails
  README.md
Labels: documentation

#217 Issue #216 - Update geckodriver to 0.26.0
  Dockerfile
Labels: enhancement

#234 Issue #233 - Upgrade Firefox to version 72.0
  Dockerfile
  README.md
Labels: enhancement

#232 Issue #229 - Add variable to mount the directories for tests and reports
  Dockerfile
  README.md
  bin/run-tests-in-virtual-screen.sh
Labels: enhancement

#235 Revert "Add robot user"
  Dockerfile
Labels: bug
